name: On PR Merge

on:
  pull_request:
    types:
      - synchronize

jobs:
  on_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Merge
        if: github.event.pull_request.merged == true
        run: |
          echo "This workflow runs when a pull request is merged."
          # You can add more steps to perform actions when a PR is merged.
