name: Reward Payout

on:
  pull_request:
    types:
      - closed

jobs:
  reward_payout:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR creator
        id: pr_creator
        run: |
          echo "pr_creator=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://github.com/Sirjamesarua/Chimoney-Payout-Workflow-after-PR-is-merged/pulls/${{ github.event.pull_request.number }}" | jq -r '.user.login')" >> $GITHUB_ENV

      - name: Initiate Payout
        if: ${{ github.event.pull_request.merged }} == true
        run: |
          CHIMONEY_API_KEY=${{ secrets.CHIMONEY_API_KEY }}
          USER=${{ env.pr_creator }}
          AMOUNT="2"

          payout_request='{
            "chimoneys": [
              {
                "email": "$USER",
                "phone": "+916300760104",
                "valueInUSD": $AMOUNT,
                "twitter": "@pinakapani06"
              }
            ]
          }'


          response=$(curl --request POST \
            --url https://api-v2-sandbox.chimoney.io/v0.2/payouts/initiate-chimoney \
            --header "X-API-KEY: $CHIMONEY_API_KEY" \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data "$payout_request")

          echo "Chimoney API Response: $response"

          payout_link=$(echo "$response" | jq -r '.payout_link')

          if [ -n "$payout_link" ]; then
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\":\"Payment link: <${payout_link}>\"}" \
              "https://github.com/Sirjamesarua/Chimoney-Payout-Workflow-after-PR-is-merged/issues/${{ github.event.pull_request.number }}/comments"
          fi
